kind: pipeline
name: default

steps:
- name: restore-cache
  image: plugins/volume-cache
  settings:
    mount:
    - ./vendor/bundle
    - ./vendor/bin
    restore: true
  volumes:
  - name: cache
    path: /cache

- name: bundle-install
  image: ruby:2.4.6
  commands:
  - bundle install --path=vendor/bundle --binstubs=vendor/bin --clean --quiet
  environment:
    RAILS_ENV: test

- name: rebuild-cache
  image: plugins/volume-cache
  settings:
    mount:
    - ./vendor/bundle
    - ./vendor/bin
    rebuild: true
  volumes:
  - name: cache
    path: /cache

- name: config-mongoid.yml
  image: ruby:2.4.6
  commands:
  - cp -n config/samples/*.yml config/
  - cp -n config/samples/*.rb  config/
  - sed -i 's/localhost:27017/mongo:27017/g' config/mongoid.yml
  - cp -n config/defaults/webmail.yml config/
  - sed -i 's/#\ test_by:\ user/test_by:\ user/g' config/webmail.yml
  - sed -i 's/#\ test_user:/test_user:/g' config/webmail.yml
  - sed -i 's/#\ \ \ host:\ localhost/\ \ host:\ mail/g' config/webmail.yml
  - sed -i 's/#\ \ \ account:\ email/\ \ account:\ email/g' config/webmail.yml
  - sed -i 's/#\ \ \ password:\ pass/\ \ password:\ pass/g' config/webmail.yml

- name: rspec
  image: ruby:2.4.6
  commands:
  # chrome
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - apt-get update && apt-get install -y google-chrome-stable
  # font
  - apt install -y fonts-ipafont fonts-ipaexfont && fc-cache -fv
  # rspec
  - cd /drone/src
  - cat config/webmail.yml
  - bundle check --path=vendor/bundle
  - bundle exec rspec spec/features/gws/users_spec.rb
  #- bundle exec rspec spec/features/article
  #- bundle exec rspec spec/features/article/pages/contact_spec.rb
  #- bundle exec rspec spec/features/article/pages/opendata_ref_individual_resources_spec.rb
  environment:
    RAILS_ENV: test
    sandbox: 1
    allow_open_jtalk: 1
    ldap_host: 153.122.23.169

services:
- name: mongo
  image: mongo:3.4
  command: [ --smallfiles, --logpath=/dev/null ]
  ports:
  - 27017

volumes:
- name: cache
  host:
    path: /tmp/cache/drone-shirasagi
