kind: pipeline
name: default

steps:
- name: config-mongoid.yml
  image: ruby:2.4.6
  commands:
  - cp -n config/samples/*.yml config/
  - cp -n config/samples/*.rb  config/
  - sed -i 's/localhost:27017/mongo:27017/g' config/mongoid.yml

- name: config-webmail.yml
  image: ruby:2.4.6
  commands:
  - cp -n config/defaults/webmail.yml  config/
  - sed -i 's/host:\ localhost/host:\ mail/g' config/webmail.yml
  - cat config/webmail.yml
  - cat config/mongoid.yml

services:
- name: mongo
  image: mongo:3.4
  command: [ --smallfiles, --logpath=/dev/null ]
  ports:
  - 27017

volumes:
- name: cache
  host:
    path: /tmp/cache/drone-shirasagi
